default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: rupauls_drag_race_development

test:
  <<: *default
  database: rupauls_drag_race_test

production:
  <<: *default
  database: rupauls_drag_race_production
